# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  username: <%= ENV["DB_USERNAME"] || "root" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>
  host:     <%= ENV["DB_HOST"] || "127.0.0.1" %>
  port:     <%= ENV["DB_PORT"] || "3306" %>

development:
  <<: *default
  database: <%= ENV["DB_NAME_DEV"] || "myapp_development" %>

test:
  <<: *default
  database: <%= ENV["DB_NAME_TEST"] || "myapp_test" %>

production:
  primary:
    <<: *default
    database: <%= ENV["DB_NAME"] || "myapp_production" %>
    ssl_mode: verify_identity
    ssl_ca:   /etc/ssl/certs/ca-certificates.crt
  cache:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
    url:  <%= ENV["SOLID_DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
    url:  <%= ENV["SOLID_DATABASE_URL"] %>
    migrations_paths: db/queue_migrate