source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.4.6"

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# 環境毎の設定管理を行う
gem "config"

# MySQLに接続する
gem "mysql2", "~> 0.5.7"

# pumaサーバーを使えるようにする（標準gem）
gem "puma", "~> 6.4"

# cors設定を管理する
gem "rack-cors"

# rails本体（標準gem）
gem "rails", "~> 8.0", ">= 8.0.3"

# タイムゾーン情報を提供する（標準gem）
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# User モデルで has_secure_password を提供する
gem "bcrypt", "~> 3.1", ">= 3.1.12"

# 言語の翻訳や多言語サポート機能を提供する
gem "rails-i18n", "~> 8.1"

# キャッシュをデータベースに保存する
gem "solid_cache", "~> 1.0", ">= 1.0.10"

group :development, :test do
  # テスト用データを作成する
  gem "factory_bot_rails"
  gem "faker"

  # pry コンソールを使えるようにする。
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  # テストフレームワーク rspec を導入する
  gem "rspec-rails"

  # rubocop を使えるようにする。
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

group :development do
  # 　開発環境用にメールをブラウザで確認する
  gem "letter_opener"
end
